### ISSUE TITLE
Listed as unstable

### ISSUE THREAD

**Issue by kdenhartog** [StableLib/stablelib#10]
I see that in the description section this is labeled as unstable. Is it only certain packages that are unstable or is the whole aspect considered unstable at this point? I'd like to use packages in here in a variety of OS projects.

**Comment by dchest** [comment]
The code is pretty solid and can be used in production if you don't mind occasional breaking changes in minor versions. That is I don't promise that API won't change, which is in line with semver (versions before 1.0.0 don't guarantee stable API). This applies to all packages. I don't have any plans change anything for some time, though, and the further development is pretty slow. I'm pretty sure you'll have to painfuly upgrade most other third-party npm packages before you'll hit a problem with updating StableLib :-)

**Comment by kdenhartog** [comment]
Awesome! This is good to hear. Thanks for the quick response as well.
