### ISSUE TITLE
@stablelib/random unable to resolve module `crypto` in react native

### ISSUE THREAD

**Issue by kenhuang** [StableLib/stablelib#14]
Reference `@stablelib/random` in RN app result unable to resolve module `crypto` error.

A possible fix is to add the following to package.json, this should allow RN env bypass `crypto` package.
```
  "react-native": {
    "crypto": false
  }
```

<img width="439" alt="Screen Shot 2019-11-01 at 5 00 23 PM" src="https://user-images.githubusercontent.com/205194/68070094-7e907f00-fdce-11e9-84fa-7ff599153419.png">

**Comment by dchest** [comment]
What does it use instead for randomBytes in this case?

**Comment by dchest** [comment]
Last time I checked, RN didn't have any random number generator, is this correct? People used https://github.com/ReactWindows/react-native-randombytes or something else -- will setting `"crypto": false` make it still possible to use those?

**Comment by kenhuang** [comment]
We are using react-native-securerandom, https://github.com/rh389/react-native-securerandom

For our usage we don’t use the crypto related functions, fix above just try to avoid RN package manage blowout on start.

**Comment by dchest** [comment]
OK, got it. Merged and published.
