### ISSUE TITLE
Scrypt constructor should cache tmp array as well

### ISSUE THREAD

**Issue by palant** [StableLib/stablelib#2]
Right now, the `tmp` array is created on every `smix()` call. While that's only 64 bytes, causing memory churn here is unnecessary - this array can be cached in the `Scrypt` constructor, same as `XY` and `V` arrays.

**Comment by dchest** [comment]
I think I benchmarked it, and it turned out to be slower, but maybe it's false memory. Maybe allocation sinking in JS engines took care of it.

**Comment by palant** [comment]
At least in my benchmarking I didn't see any significant difference.

**Comment by dchest** [comment]
Good, thanks! I also benchmarked it (with N=8, r=8, p=500, since it allocates once per *p*), and saw no difference in Node 8, so I think this allocation is sinked by V8. Let's keep it as it is, since this would be an unnecessary optimization.

**Comment by palant** [comment]
I actually meant that there is no performance difference, I'm not really convinced that there is no impact on memory.
