### ISSUE TITLE
yarn should be listed as a dependency

### ISSUE THREAD

**Issue by palant** [StableLib/stablelib#3]
Running tests currently fails because yarn cannot be found. I assume that you have it installed globally, but it doesn't have to be. Running `npm install yarn` fixes this issue, so it should be added to devDependencies.

**Comment by dchest** [comment]
Hmm, I'm not sure. It's a package manager that replaces `npm`, and I have it installed globally via `brew`, not `npm`. I don't want to have it installed locally in `node_module`. Anyway, I think I'll switch to `npm5` in the near future — once they fix those tons of bugs with package locks, so it wouldn't be a problem.
