### ISSUE TITLE
Please support 256-bit secret keys in Ed25519

### ISSUE THREAD

**Issue by maurictg** [StableLib/stablelib#45]
When I'm using the function `ed25519.extractPublicKeyFromSecretKey()` with a 32-byte secret key I get the following error: 
`
Error: ed25519: secret key must be 64 bytes
`

I want to exchange private keys with other libraries in other languages (like libsodium, NSec.Cryptography etc) and they all use 32-byte s private keys. However, signed messages with the 64-bytes secret key in the stablelib ed25519 library, verified with one of the mentioned libraries above works fine.

Can you please add support for (importing) 256-bits/32-bytes keys?

**Comment by dchest** [comment]
Use generateKeyPairFromSeed where seed is the 32-byte private key from other library.

**Comment by maurictg** [comment]
Great, that works fine! Thank you for your fast response! Is there also a way to do it vice-versa, i.e. extracting seed from private key?

**Comment by maurictg** [comment]
Great, that works fine!
