### ISSUE TITLE
salsaXOR() unnecessarily increments the counter in steps of 2

### ISSUE THREAD

**Issue by palant** [StableLib/stablelib#5]
[Here](https://github.com/StableLib/stablelib/blob/14a28f1167ecb6c18c11e9a9d57deeb0f7214aff/packages/scrypt/scrypt.ts#L249) the loop implementing Salsa20 algorithm looks like this:

     for (let i = 0; i < 8; i += 2) {

Given that the loop index isn't used, there are really only four loop iterations and the following code is equivalent:

    for (let i = 0; i < 4; i++) {

Unless I'm somehow mistaken, that should be simplified to avoid confusion (it definitely confused me).

**Comment by dchest** [comment]
It's like this just to show that the number of rounds is 8. Pretty typical of Salsa20 implementations, e.g. see https://cr.yp.to/salsa20.html (20 rounds, each iteration is 2 rounds).
