### ISSUE TITLE
Support for BLS12-381 curve

### ISSUE THREAD

**Issue by dsawali** [StableLib/stablelib#61]
Hello there, just wondering if Stablelib could support BLS12-381 curve. It's a quite popular cryptography curve used in ETH as well as Tezos blockchain. 

It would be great to have support for this.

relevant links:
- https://neuromancer.sk/std/bls/BLS12-381

**Comment by paulmillr** [comment]
I don't think elliptic curves are in scope of stablelib.

https://github.com/paulmillr/noble-curves supports bls12-381.
