### ISSUE TITLE
Inquiry About LibSodium Method Support in stablelib

### ISSUE THREAD

**Issue by mrtnetwork** [StableLib/stablelib#64]
Thank you for the great package. I'm interested in using some specific LibSodium methods, and I wanted to confirm if the package supports the following methods:

`crypto_core_ed25519_add`
`crypto_scalarmult_ed25519`
`crypto_scalarmult_ed25519_base`
`crypto_core_ed25519_scalar_reduce`

Could you please provide information on whether these methods are available and if there are any usage examples or documentation related to them? Your assistance is greatly appreciated.

**Comment by dchest** [comment]
Hello,

No, StableLib doesn't have these methods.  Perhaps, your best solution would be to use a WASM-compiled libsodium.
