### ISSUE TITLE
CommonJS support (again!)

### ISSUE THREAD

**Issue by damiensawyer** [StableLib/stablelib#69]
Hi, please forgive me if I'm off piste with this question. I'm still working my way around commonj vs modules. 

I'm wondering why a CJS version isn't included in your build output.

I've read [this](https://github.com/StableLib/stablelib/pull/51) and it seems that you considered compiling to both but moved away. 

My project is Typescript, using Jest. The [Jest docs](https://jestjs.io/docs/ecmascript-modules) have a huge warning that module support is experiement. Also, according to [state of JS](https://2023.stateofjs.com/en-US/libraries/testing/), Jest is still king of the hill.

I've wrestled for 2 hours this morning trying to get stablelib modules working in our monorepo, but - and I guess it's me - I just can't get Jest to play nice. 

I love TypeScript. I love modules. I love this project you've put together - but given the continued dependence by some popular tooling on CJS, would it be possible for StableLib to compile to both?

Sorry If I'm missing something obvious.

Thanks for listening to my rant :-)

**Comment by damiensawyer** [comment]
Forget all of that. I switched to Vitest and life is _awesome_. 
Good riddance to CommonJS.

**Comment by dchest** [comment]
Haha, yeah, CommonJS is pretty much dead, and those who wish to use it could use some bundler/preprocessor (or keep using 1.x versions of the StableLib packages).

I also had issues with Jasmine and Jest, so I switched to Vitest  :D

**Comment by damiensawyer** [comment]
It makes me wonder why Jest has not only so much market share but also such
positive community sentiment.

I guess that following the crowd isn't always a great idea.

I've been looking through the stablelib code today.  It's a thing of
beauty.  Your attention to correctness is a real joy 😊 .
