### ISSUE TITLE
[Feature Request] Please add the module for crc32 and int64(long)

### ISSUE THREAD

**Issue by XuJinNet** [StableLib/stablelib#8]
This library is very practical.
Can you add the module for crc32 and int64(long)?

**Comment by dchest** [comment]
I'm not sure about crc32, but what do you mean by int64(long)? A class to handle 64-bit integers? If so, newer JS versions have `BigInt`, which covers it, so I don't think I'll add it (for older browsers if necessary, there should be a shim.)

**Comment by XuJinNet** [comment]
Thanks!
What about a module for MD5?

**Comment by dchest** [comment]
MD5 is broken and shouldn't be used anymore.

**Comment by XuJinNet** [comment]
Thanks!
